/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICollectionWhitelistChecker } from "./ICollectionWhitelistChecker";
export type { IERC165 } from "./IERC165";
export type { IERC721 } from "./IERC721";
export type { IERC721Metadata } from "./IERC721Metadata";
export type { IERC721Receiver } from "./IERC721Receiver";
export type { IGTS20 } from "./IGTS20";
export type { IWGANG } from "./IWGANG";
