/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721Holder } from "./ERC721Holder";
export type { ERC721URIStorage } from "./ERC721URIStorage";
