/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPancakeBunnies,
  IPancakeBunniesInterface,
} from "../../../contracts/interfaces/IPancakeBunnies";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "getBunnyId",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPancakeBunnies__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeBunniesInterface {
    return new utils.Interface(_abi) as IPancakeBunniesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPancakeBunnies {
    return new Contract(address, _abi, signerOrProvider) as IPancakeBunnies;
  }
}
