/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GTS20Snapshot_UPG } from "./GTS20Snapshot_UPG";
export type { GTS20_UPG } from "./GTS20_UPG";
export type { ScheduledTokenLock } from "./ScheduledTokenLock";
export type { TokenLock } from "./TokenLock";
