/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGTS20__factory } from "./IGTS20__factory";
export { INobleCallee__factory } from "./INobleCallee__factory";
export { INobleFactory__factory } from "./INobleFactory__factory";
export { INobleGTS20__factory } from "./INobleGTS20__factory";
export { INobleMigrator__factory } from "./INobleMigrator__factory";
export { INoblePair__factory } from "./INoblePair__factory";
export { INobleRouter01__factory } from "./INobleRouter01__factory";
export { INobleRouter02__factory } from "./INobleRouter02__factory";
export { IWGANG__factory } from "./IWGANG__factory";
