/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  INobleCallee,
  INobleCalleeInterface,
} from "../../interfaces/INobleCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "nobleCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INobleCallee__factory {
  static readonly abi = _abi;
  static createInterface(): INobleCalleeInterface {
    return new utils.Interface(_abi) as INobleCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INobleCallee {
    return new Contract(address, _abi, signerOrProvider) as INobleCallee;
  }
}
