/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GTS20Upgrade__factory } from "./GTS20Upgrade__factory";
export { UUPSUpgradeable__factory } from "./UUPSUpgradeable__factory";
