/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC165 } from "./ERC165";
export type { ERC721 } from "./ERC721";
export type { GTS20 } from "./GTS20";
export type { WGANG } from "./WGANG";
