/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockGTS20__factory } from "./MockGTS20__factory";
export { MockNFT__factory } from "./MockNFT__factory";
